// <auto-generated />
using System;
using MarsThreeSite.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarsThreeSite.Migrations
{
    [DbContext(typeof(SiteDb))]
    [Migration("20181012204845_PageMigration")]
    partial class PageMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MarsThreeSite.Models.CommentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommentText")
                        .IsRequired();

                    b.Property<DateTime>("CreatedDate");

                    b.HasKey("Id");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("MarsThreeSite.Models.PageIdentity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PageNumber");

                    b.HasKey("Id");

                    b.ToTable("PageIdentity");
                });

            modelBuilder.Entity("MarsThreeSite.Models.PageModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("PageAdress");

                    b.Property<int?>("PageIdId");

                    b.HasKey("Id");

                    b.HasIndex("PageIdId");

                    b.ToTable("Pages");
                });

            modelBuilder.Entity("MarsThreeSite.Models.PageModel", b =>
                {
                    b.HasOne("MarsThreeSite.Models.PageIdentity", "PageId")
                        .WithMany()
                        .HasForeignKey("PageIdId");
                });
#pragma warning restore 612, 618
        }
    }
}
